#!/bin/bash
VENV="~/.virtualenvs/mbs2_new/bin/activate"

export PYTHONPATH=~/workspace/asexor:~/workspace/mybookshelf2
#export PYTHONPATH=~/workspace/mybookshelf2

gnome-terminal \
--tab  -e "bash --rcfile $VENV" \
--tab  -e "bash --rcfile $VENV" \
--tab  -e "bash --rcfile $VENV" \
--tab  -e "bash --rcfile $VENV"
