FROM mbs2-ubuntu

MAINTAINER ivan

RUN wget http://nginx.org/keys/nginx_signing.key &&\
    apt-key add nginx_signing.key &&\
    echo "deb http://nginx.org/packages/ubuntu/ `lsb_release -cs` nginx" >> /etc/apt/sources.list.d/nginx.list &&\
    apt-get update &&\
    apt-get install -y nginx &&\
    pip3 install uwsgi
    
WORKDIR /code

