FROM ubuntu:12.04

MAINTAINER ivan

RUN apt-get update &&\
    apt-get install -y python-software-properties wget libffi-dev  git build-essential &&\
		add-apt-repository -y  ppa:fkrull/deadsnakes &&\
		sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list' &&\
		wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add - &&\
		apt-get update &&\
		apt-get install -y python3.5 libpq-dev python3.5-dev &&\
		ln -s /usr/bin/python3.5 /usr/bin/python3 &&\
		wget https://bootstrap.pypa.io/get-pip.py &&\
    python3 get-pip.py &&\
    rm get-pip.py
    
RUN locale-gen en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
    
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip3 install -r requirements.txt
RUN mkdir /crossbar
ADD crossbar.config.json /crossbar/config.json
ADD ssl/server.cert.pem /crossbar/
ADD ssl/server.key.pem /crossbar/



