FROM mbs2-ubuntu

MAINTAINER ivan

#FOR backend
# 12.04 dependencies
# add-apt-repository ppa:libreoffice/libreoffice-5-0 &&\
#TBD - add libreoffice version to env variables
RUN apt-get update &&\
    apt-get install -y imagemagick libreoffice libgl1-mesa-glx
    
RUN wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin version=5.44.0

EXPOSE 8080 9080
		
ADD loop.sh /

